version: '3'
services:
  kafka-zookeeper:
    image: confluentinc/cp-zookeeper:4.0.1
    hostname: kafka-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - webnet
  kafka-broker:
    image: confluentinc/cp-enterprise-kafka:4.0.1
    hostname: kafka-broker
    depends_on:
      - kafka-zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'kafka-zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - webnet
  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest:4.0.1
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082/
      KAFKA_REST_HOST_NAME: kafka-rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka-broker:9092
    depends_on:
      - kafka-zookeeper
      - kafka-broker
    networks:
      - webnet
  kafka-topics-ui:
    image: landoop/kafka-topics-ui
    environment:
      PROXY: "true"
      KAFKA_REST_PROXY_URL: http://kafka-rest-proxy:8082
      PORT: 8001
    ports:
      - "8001:8001"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
